### ISSUE TITLE
Support for other DBMSs/Connection Pool

### ISSUE THREAD

**Issue by mppfiles** [anjulgarg/wings-framework#1]
Please add suport for other DBMS (particularly PostgreSQL) and Connection Pools.

**Comment by anjulgarg** [comment]
Hi, I plan to add these features in the next release of Wings. 
This is the semester end in my college and I am extremely busy with my academics, thus I am looking for contributors who can help me with these features.
I will try to increase DB support very soon.

Thanks for raising the issue. :)

**Comment by allebb** [comment]
👍
